import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'vndj',
    description: 'Generated by Next Editor Studio',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="antialiased">
                {children}
            </body>
        </html>
    );
}